Fixes #431 Make textarea expand automatically
fossasia/susi_chromebot pull request #432
Opened 2018-10-10 20:25 UTC by satyamtg

Fixes #431 

#### Checklist

- [x] I have read the [Contribution & Best practices Guide](https://blog.fossasia.org/open-source-developer-guide-and-best-practices-at-fossasia) and my PR follows them.
- [x] My branch is up-to-date with the Upstream `master` branch.
- [x] The unit tests pass locally with my changes 
- [x] I have added tests that prove my fix is effective or that my feature works
- [x] I have added necessary documentation (if appropriate)
- [x] All the functions created/modified in this PR contain relevant docstrings.

#### Short description of what this resolves:
This makes the textarea to type messages expand and contract vertically according to the size of message which is being typed in real time. This makes reviewing the messages before posting them easier as compared to previous scrollbar implementation.

![expected](https://user-images.githubusercontent.com/17774888/46763418-621f3180-ccf7-11e8-94fb-61115561f4f8.gif)

#### Changes proposed in this pull request:

-Make textarea to type messages expand and contract vertically according to the size of the message being typed.

2018-10-14 09:11 UTC, fragm3 requested changes
The Text Area is always fixed

2018-10-14 16:23 UTC, rossoskull reviewed
Agree with @fragm3. Maybe you can increase the size for 2-3 lines, but not more than that :thinking:

2018-10-21 17:22 UTC, akshatnitd requested changes

2018-10-22 12:50 UTC, gabru-md commented on src/script.js
> +    element.style.cssText = "height:auto";
@satyamtg  can you please look into the changes pointed by akshat.
Once done please ask for a review again. thank you

2018-10-22 12:56 UTC, gabru-md commented on src/script.js
> +    element.style.cssText = "height:auto";
@satyamtg  can you please look into the changes pointed by akshat.
Once done please ask for a review again. thank you

2018-12-06 08:46 UTC, the-codingninja requested changes
Please do the suggested changes

2025-10-30 14:18 UTC, closed without merging